### ISSUE TITLE
'pip install nose-cprof' fails -- No such file README.md

### ISSUE THREAD

**Issue by liv42da** [msherry/nose-cprof#3]
It looks like README.md might simply be missing from the tar.  Here are steps to reproduce and the callstack:

**$ pip install nose-cprof**

```
Downloading/unpacking nose-cprof
  Downloading nose-cprof-0.1-2.tar.gz
  Running setup.py egg_info for package nose-cprof
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-user/nose-cprof/setup.py", line 12, in <module>
        with open(os.path.join(PATH_TO_FILE, 'README.md')) as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-user/nose-cprof/README.md'
```

And downloading the tar from pypi confirms that README.md is missing:

**$ tar -tvf ~/Downloads/nose-cprof-0.1-2.tar.gz** 

```
drwxr-xr-x marc/staff        0 2016-09-08 14:05 nose-cprof-0.1-2/
-rw-r--r-- marc/staff       50 2016-09-08 13:36 nose-cprof-0.1-2/MANIFEST.in
drwxr-xr-x marc/staff        0 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprof.egg-info/
-rw-r--r-- marc/staff        1 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprof.egg-info/dependency_links.txt
-rw-r--r-- marc/staff       61 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprof.egg-info/entry_points.txt
-rw-r--r-- marc/staff        1 2016-09-08 13:40 nose-cprof-0.1-2/nose_cprof.egg-info/not-zip-safe
-rw-r--r-- marc/staff     1901 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprof.egg-info/PKG-INFO
-rw-r--r-- marc/staff       13 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprof.egg-info/requires.txt
-rw-r--r-- marc/staff      326 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprof.egg-info/SOURCES.txt
-rw-r--r-- marc/staff       14 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprof.egg-info/top_level.txt
drwxr-xr-x marc/staff        0 2016-09-08 14:05 nose-cprof-0.1-2/nose_cprofile/
-rw-r--r-- marc/staff       78 2016-09-08 13:45 nose-cprof-0.1-2/nose_cprofile/__init__.py
-rw-r--r-- marc/staff     2113 2016-09-08 13:56 nose-cprof-0.1-2/nose_cprofile/nose_cprofile.py
-rw-r--r-- marc/staff     1901 2016-09-08 14:05 nose-cprof-0.1-2/PKG-INFO
-rw-r--r-- marc/staff       59 2016-09-08 14:05 nose-cprof-0.1-2/setup.cfg
-rw-r--r-- marc/staff     1365 2016-09-08 13:58 nose-cprof-0.1-2/setup.py
```

**Comment by msherry** [comment]
Oops, you're right. I revamped the docs recently and accidentally broke the packaging. 0.1.4 is on PyPi now and should fix this. Thanks for reporting!
